### ISSUE TITLE
Additional features wish to have

### ISSUE THREAD

**Issue by lee1043** [PCMDI/d3_chart#4]
@William-Hill thanks for setting up the repo and demo, which looks great. I am opening this issue page to discuss additional features that @gleckler1 and I'd like to have. Few things came up to me as first is like below:
- [x] mouse hover over symbol shows model name as small pop-up
- [x] clicking symbol activate lines; similar to clicking row on table below
- [x] line to have same color as symbol
- [x] optimization for small screen size, such as for laptop
- [x] legend in vertical
- [x] option to adjust y-axis range
- [x] table row to have same color as line when selected
- [x] buttons for select all and unselect all

#### Below is for a screen capture on my MacBook Air:
![Screen Shot 2019-06-05 at 6 41 36 AM](https://user-images.githubusercontent.com/17091564/58915927-25f48180-875d-11e9-9ad2-82ed177a782b.png)

**Comment by durack1** [comment]
@lee1043 it would be worthwhile thinking about tablet/phone access to these pages in addition to a smaller laptop screen - most folks browse such pages first on a tablet/phone, particularly while attending a seminar or conference

**Comment by William-Hill** [comment]
- [ ] mouse hover over symbol shows model name as small pop-up -> resolved by PR #5; changes are live on demo site.

**Comment by William-Hill** [comment]
- [ ] clicking symbol activate lines; similar to clicking row on table below -> resolved by PR #6; ; changes are live on demo site.

**Comment by William-Hill** [comment]
- [ ]  line to have same color as symbol -> resolved by PR #7 ; changes are live on demo site

**Comment by lee1043** [comment]
@William-Hill thanks for updating. I saw they are working in the [live demo](https://pedantic-curie-f2f061.netlify.com). I added one more at the list on top, which is "option to adjust y-axis range"

**Comment by lee1043** [comment]
@durack1 agreed, good point!

**Comment by William-Hill** [comment]
- [ ] table row to have same color as line when selected -> resolved by PR #8 . ; changes are live on demo site

**Comment by William-Hill** [comment]
- [ ] buttons for select all and unselect all -> resolved by PR #9; changes are live on demo site

**Comment by lee1043** [comment]
@William-Hill updates are looking great, thanks! 

Is it possible to make selection works same in both graph and table? For example, for now when I select purple plus sign from graph (which is for ACCESS1-3), it cannot be deselected by the "Deselect All" button. It would be even more great if user click symbol on graph, which shows line, AND also highlight corresponding row of table.

**Comment by William-Hill** [comment]
- [ ] optimization for small screen size, such as for laptop

- [ ] legend in vertical

Both resolved by PR #10; changes are live on demo site

**Comment by William-Hill** [comment]
@lee1043 Good catch.  I might have to do a bit of refactoring to get that to work properly as I'll need to do something to properly manage the internal state of the web app.  Will take me a little more time to get that right.

**Comment by William-Hill** [comment]
- [ ] option to adjust y-axis range; Resolved by PR #11; changes are live on demo site

**Comment by William-Hill** [comment]
> @William-Hill updates are looking great, thanks!
> 
> Is it possible to make selection works same in both graph and table? For example, for now when I select purple plus sign from graph (which is for ACCESS1-3), it cannot be deselected by the "Deselect All" button. It would be even more great if user click symbol on graph, which shows line, AND also highlight corresponding row of table.

Fix this bug reported by @lee1043.  Changes are live

**Comment by lee1043** [comment]
@William-Hill confirmed that bug resolved at the [live demo](https://pedantic-curie-f2f061.netlify.com/) page, thank you very much. It looks nice!

**Comment by William-Hill** [comment]
Initial requirements complete
